blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/your-repo/issues/new?template=bug_report.md
    about: Report a bug or error
  - name: Feature Request
    url: https://github.com/your-repo/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
